### ISSUE TITLE
Create containerized option for running docker examples

### ISSUE THREAD

**Issue by mtheoryx** [blackboard/react-dnd-ax#1]
In order to cultivate an easy-to-view running example, we should use Docker.

- Node and NPM version are controlled
- Storybook version is controlled
- User's machine does not get polluted with any dependencies

**Comment by artecher** [comment]
@mtheoryx Thanks for the contribution! I tried it and it works perfectly. 

Can you also add `volumn` mapping in docker environment? As the user has live reload ability by running `npm run storybook` to play the examples, we'd like to keep this ability for the docker way as well.

**Comment by mtheoryx** [comment]
@artecher Great idea, I added that now, and hot reload is working!

Additionally, I added the docker configuration files to the .npmignore since we probably don't want to be shipping that around in a published module.

Cheers!
