### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by Noitidart** [blackboard/react-dnd-ax#18]
Screencast - https://i.imgur.com/vmgHAKn.mp4

**Comment by artecher** [comment]
https://github.com/blackboard/react-dnd-ax/blob/8ed740590b021259c6d87b5bb2c713a3a8470b14/src/examples/complex-example/Country.js#L21-L29
`<button/>` needs to be changed to `div` as `button` element in FF cannot trigger `dragstart` https://bugzilla.mozilla.org/show_bug.cgi?id=568313.
Will change later.
Thanks for reporting.

**Comment by artecher** [comment]
Fixed in 26fd76820cd4071188a1c296130c79326eb5628c
