### ISSUE TITLE
I think you guys missed putting license into this project.

### ISSUE THREAD

**Issue by kenshinji** [blackboard/react-dnd-ax#6]

**Comment by artecher** [comment]
Thanks for reminding us @kenshinji , License added.

**Comment by kenshinji** [comment]
np, I think you can check [this](https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba) out and add a license badge for your project, gotta be fun.

**Comment by artecher** [comment]
When clicking the `MIT` link it generated, it goes to link https://opensource.org/licenses/MIT. In the page on this link, there is a text with placeholder `Copyright <YEAR> <COPYRIGHT HOLDER>`. Is there a good way to fill these placeholders?

**Comment by artecher** [comment]
It looks cool. Added into README.MD
